### PR TITLE
Kafka 0.8 - rebased plus changes. 

### PR DESCRIPTION
**Pull request by rasjones**

### CODE REVIEW

**Comment by manub** [comment]
I couldn't possibly merge this PR with this commit history. I would suggest you to fork master as of now, apply your changes, and then submit your PR again. If you want to perform changes against the Kafka 0.8 branch let me know as that one is quite far behind.

**Comment by rasjones** [comment]
ok. i'm only interested in making a change to the kafka 0.8 branch because I'm using that. you had asked me to rebase those changes over the master branch to allow travis CI pass - which is what I'm trying to do now. 

these changes essentially 0.8 rebased over master with kafka-streams pulled out since that isn't supported on kafka 0.8. do you still want CI working on the 0.8 branch? or something else.

**Comment by manub** [comment]
Ok, that's clearer now - sorry but with all the open and closed PRs it was a bit tricky.

Don't mind about rebasing the last changes. Take kafka-0.8 as it is now and apply your changes. I will release a hotfix for that.

**Comment by rasjones** [comment]
ok. before i abandon rebasing. will a squash commit address your concern. or i should just abandon this ^^.

**Comment by manub** [comment]
I'm not planning to support 0.8 anymore so don't worry about it for now.
Sorry for the misunderstanding.

**Comment by rasjones** [comment]
ok. ill just create a smaller change. thanks for being supportive.

**Comment by rasjones** [comment]
I have made the change here. Please create a release. 
https://github.com/manub/scalatest-embedded-kafka/pull/47

**Comment by rasjones** [comment]
hi there! any word on ^^ ?

**Comment by manub** [comment]
Hi - I'm not at the computer right now so I'm sorry it will take a bit
longer.

**Comment by manub** [comment]
I've got a bad virus so you'll need a bit more patience - sorry about that

**Pull request closed without merging**
