### PR TITLE
Concurrent kafka instances

### LINKED ISSUE #101: Unable to run tests in parallel
Due to the singleton, mutable `broker` ([see here](https://github.com/manub/scalatest-embedded-kafka/blob/master/embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala#L47)). It's not possible to run tests in parallel, even when randomising ports.

If more than one test using `EmbededKafka` runs at the same time I consistently get:
```
FATAL [Replica Manager on Broker 0]: Error writing to highwatermark file:  (kafka.server.ReplicaManager:118)
java.io.FileNotFoundException: /var/folders/5l/z1qx5k790f9_h1wtxk8mj1k4pgw6zm/T/kafka-logs4978987266055584410.tmp/replication-offset-checkpoint.tmp (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at kafka.server.checkpoints.CheckpointFile.write(CheckpointFile.scala:43)
        at kafka.server.checkpoints.OffsetCheckpointFile.write(OffsetCheckpointFile.scala:58)
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$5(ReplicaManager.scala:1118)
        at kafka.server.ReplicaManager.$anonfun$checkpointHighWatermarks$5$adapted(ReplicaManager.scala:1115)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:120)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
        at kafka.server.ReplicaManager.checkpointHighWatermarks(ReplicaManager.scala:1115)
        at kafka.server.ReplicaManager.$anonfun$startHighWaterMarksCheckPointThread$1(ReplicaManager.scala:211)
        at kafka.utils.KafkaScheduler.$anonfun$schedule$2(KafkaScheduler.scala:110)
        at kafka.utils.CoreUtils$$anon$1.run(CoreUtils.scala:57)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I think it would make sense that `start()` returned a new instance of `KafkaServer` each time it is called.

### PR DESCRIPTION
**Pull request by tjheslin1**
```
THIS IS A WORK IN PROGRESS
```

Functionally the changes are made. I would like to make some refactorings first and also look into the query raised by @shashidesai.

I'm raising this PR now in the hopes that you can take a look at my approach. If you have any major concerns it would be best to find out sooner!

Closes #101 

TODO:

- [x] @shashidesai's query around `runStreams`
- [x] ~implicit conversion~ extension  method to go from `Seq[EmbeddedServer]` => `Seq[EmbeddedZ]` or `Seq[EmbeddedK]`, replacing the boiler place `isInstanceOf` + `asInstanceOf`
- [x] clean up of new tests for conciseness
- [x] javadoc for `EmbeddedServer.scala`

## Problem

Running tests in parallel which use `EmbeddedKafka` can run into an issue with the log files as `EmbeddedKafka#stop` clears all temporary log directories, which another instance of kafka may still be relying on in another test.

To see this error I changed `logback.xml` line 1 to: `log4j.rootLogger=error,stdout`:

`FATAL [Replica Manager on Broker 0]: Error writing to highwatermark file` ... `java.io.FileNotFoundException` ... `kafka-logsXXXXXXXXX.tmp/replication-offset-checkpoint.tmp (No such file or directory)`

## Testing

_I would like to improve these as there is quite a lot of repetition_

- [start and stop a specific Kafka](https://github.com/tjheslin1/scalatest-embedded-kafka/blob/concurrent-kafka/embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaObjectSpec.scala#L38)
- [start and stop multiple Kafka instances on specified ports](https://github.com/tjheslin1/scalatest-embedded-kafka/blob/concurrent-kafka/embedded-kafka/src/test/scala/net/manub/embeddedkafka/EmbeddedKafkaObjectSpec.scala#L59)

## Solution

I have created a model of the running servers, both Kafka and Zookeeper. Starting one of these appends an `EmbeddedServer` to managed list of `servers`.

The following functions have had their signatures modified. Given that they all used to return `Unit`, this results in a non-breaking change to users. On upgrading the returned objects will be ignored and the existing functionality will be preserved.

[EmbeddedKafka#start](https://github.com/tjheslin1/scalatest-embedded-kafka/blob/concurrent-kafka/embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala#L39) now returns an `EmbeddedServer`.

[EmbeddedKafka#startZooKeeper](https://github.com/tjheslin1/scalatest-embedded-kafka/blob/concurrent-kafka/embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala#L57) now returns an `EmbeddedZ`.

[EmbeddedKafka#startKafka](https://github.com/tjheslin1/scalatest-embedded-kafka/blob/concurrent-kafka/embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala#L71) now returns an `EmbeddedK`.

I have added an overload to [EmbeddedKafka#stop](https://github.com/tjheslin1/scalatest-embedded-kafka/blob/concurrent-kafka/embedded-kafka/src/main/scala/net/manub/embeddedkafka/EmbeddedKafka.scala#L91) which will stop the specific server and remove it from the list of managed servers.

### CODE REVIEW

**Comment by manub** [comment]
Thanks @tjheslin1 - the approach looks good to me. Let me know when you've finished and I'll carry on with the review.

**Comment by tjheslin1** [comment]
Ready to be reviewed.

**Comment by manub** [comment]
All looks good - could you please address the 2 minor things that are still pending?

**Comment by tjheslin1** [comment]
Ready now @manub. @shashidesai will be raising another issue.

**Comment by manub** [comment]
Thanks. Will merge now and release in the next days.

**Pull request merged**
