### PR TITLE
Switch to Kafka 0.10.1.0

### PR DESCRIPTION
**Pull request by kciesielski**

### CODE REVIEW

**Comment by manub** [comment]
@kciesielski thanks for this. I'm planning to merge #39 before this as soon as the comments are addressed. Would that work for you or this is a blocker for https://github.com/akka/reactive-kafka?

**Comment by kciesielski** [comment]
@manub we just agreed that we'll stay with older version for now, so this doesn't block us.

**Comment by manub** [comment]
@kciesielski could you rebase master please?

**Comment by kciesielski** [comment]
rebased

**Comment by manub** [comment]
Thanks @kciesielski - will release this in the next couple of weeks.

**Pull request merged**
