### PR TITLE
Upgrade to kafka 0.10.0.1

### PR DESCRIPTION
**Pull request by 13h3r**

### CODE REVIEW

**Comment by 13h3r** [comment]
Could you also please release next public version?

**Comment by manub** [comment]
Yes - I'm planning to do it later on today or tomorrow the latest. The release will be `0.7.1`.

**Comment by manub** [comment]
@13h3r version `0.7.1` has now been released on Bintray and Maven Central.

**Comment by 13h3r** [comment]
Thanks!

**Pull request merged**
